### PR TITLE
Updated to use DEVELOPMENT-SNAPSHOT-2016-07-25-a

### PR DESCRIPTION
**Pull request by NathanFlurry**

### CODE REVIEW

**Comment by nbransby** [comment]
Hey thanks Nathan, this is great. I had not had the chance to update to latest beta.

Re the formatting, did you use a formatter in an IDE to do it? Would like to make sure the [complier](https://github.com/crossrails/compiler) is also outputting best practice formatted Swift.

**Comment by NathanFlurry** [comment]
@nbransby I just used some find + replace + a tad of regex magic in Xcode.

As for code styling, I'd highly suggest taking a look at this [styling guide](https://github.com/raywenderlich/swift-style-guide). Just some quick feedback from what I saw was generated from crossrails:
- Colons are usually used as `parameterName: Type` (not `parameterName :Type`) for functions, variable definitions, etc..
- Limit your use of `try!` in Swift, since you can't catch those error with `do { } catch { }` (aka the app will crash entirely if it fails). Either return an optional type if the operation failed or throw/rethrow the error. The same applies for implicitly unwrapped variables, always try to make them optional values if possible. Attempting to access a nil value in an implicitly unwrapped optional will throw an uncatchable error.
- File names tend to use upper camel case, e.g. `simpleObject.swift` should be `SimpleObject.swift`
- Don't do [this](https://github.com/crossrails/compiler/blob/master/tests/swift/src/simpleObject.swift#L58). Use the `===` operator if you're trying to compare the object reference. If your'e trying to compare the object's values, you'll have to implement it manually.
- I'd suggest using an `enum` for the message type in `SpecialException`. It'll make your life easier if you try and localize or create a standardized error code register.

Otherwise, it looks like a very promising project.

**Comment by Reedyuk** [comment]
Just a thought, maybe we should run something like SwiftLint on the results to check for this kind of thing?

**Comment by nbransby** [comment]
Thanks for the feedback @NathanFlurry, I've finally found the time to act on it.
- Colons moved to match the style guide
- Updated the object equality check

The other points you mentioned are by design and are moviated to match the orginal JS source:
- Method calls are generated with try! if the JS code is not declared to throw anything (using the @throws JSDoc tag)
- File name case is preserved from the js filenames
- SpecialException is a generated file from the test/input TS source

**Pull request merged**
